# docker build -t biopy3-simple -f Dockerfile.simple .
FROM ubuntu:bionic
ENV LANG=en_US.UTF-8
RUN env LANG=C apt-get update -qq \
    && env LANG=C DEBIAN_FRONTEND=noninteractive apt-get install -yqq \
        locales ca-certificates python3 \
    && echo "$LANG UTF-8" >/etc/locale.gen \
    && locale-gen --lang "$LANG"
ENTRYPOINT ["python3"]
